---
title: Высотное обследование.рф
timezone: Europe/Moscow
encoding: UTF-8


sass:
  style: compressed
  sourcemap: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

theme: ""
permalink: /:title/:slug


collections:
  portfolio:
    output: true
    permalink: /portfolio/:title
  v2:
    output: true
    permalink: /v2/:title
    


defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    permalink: /:title
    layout: "uni"
- scope:
    path: "_v2" 
  values:
    permalink: /:collection/:name
    layout: "v2"
    sitemap: false

# jekyll-seo-tag
description: "Методы и средства оценки технического состояния механизмов, оборудования, конструкций и других технических объектов в труднодоступных местах, установление причин неисправностей, рекомендации по устранению их причин."
logo: "/img/eagle.png"
lang: ru_RU

