---
title: Altitude Survey.Github.io v0.2
timezone: Europe/Moscow

sass:
    sourcemap: true

include: ["./index.json"]
   

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "uni"
