---
title: Altitude Survey.Github.Io
timezone: Europe/Moscow
collections:
  blocks:
    title: Blocks
    output: false
  v2:
    title: V2
    output: true
    sort_by: sortid

defaults:
  -
    scope:
      path: "v2" # an empty string here means all files in the project
    values:
      layout: "uni"