---
title: Высотное обследование.рф
timezone: Europe/Moscow


sass:
  style: compressed
  sourcemap: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  portfolio:
    output: true
    layout: portfolio
    permalink: /portfolio/:title
  v2:
    output: true
    layout: v2
    permalink: /v2/:title
    


defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    # permalink: /:name/:title/:slug/
    layout: "uni"
- scope:
    path: "v2" 
  values:
    # permalink: /:name/:title/:slug/
    layout: "v2"

# jekyll-seo-tag
description: "Методы и средства оценки технического состояния механизмов, оборудования, конструкций и других технических объектов в труднодоступных местах, установление причин неисправностей, рекомендации по устранению их причин."
logo: "/img/eagle.png"
lang: ru_RU

