---
title: Altitude Survey.Github.io v0.2
timezone: Europe/Moscow

collections_dir: collections

sass:
  style: compressed
  sourcemap: true

plugins:
  - jekyll-sitemap
  # - jekyll-seo-tag

collections:
  - gal_3.1:
      output: true




defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "uni"
