---
title: Высотное обследование.рф
timezone: Europe/Moscow


sass:
  style: compressed
  sourcemap: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  portfolio:
    output: true
    layout: "portfolio"
    permalink: /portfolio/:title
    


defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    permalink: /:title/:slug/
    layout: "uni"

# jekyll-seo-tag
description: "Методы и средства оценки технического состояния механизмов, оборудования, конструкций и других технических объектов в труднодоступных местах, установление причин неисправностей, рекомендации по устранению их причин."
logo: "/img/eagle.png"
lang: ru_RU

