---
title: Высотное обследование
timezone: Europe/Moscow


sass:
  style: compressed
  sourcemap: true

plugins:
  - jekyll-sitemap
  # - jekyll-seo-tag

collections:
  portfolio:
    output: true
    layout: "portfolio"
    permalink: /portfolio/:title
    


defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "uni"

