---
title: Altitude Survey.Github.io v0.2
timezone: Europe/Moscow

sass:
  style: compressed
  sourcemap: true

plugins:
  - jekyll-sitemap
  # - jekyll-seo-tag

collections_dir: collections


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "uni"
